version: "3.9"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      bridge:
       ipv4_address: 172.19.0.12
    environment:
      NODE_ENV: development
